title: Product
pages: false
files: true
  sortable: true
  fields:
    title:
      label: Alt Tag
      type: text
fields:
  title:
    label: Title
    type:  text
  price:
    label: price
    type: number
  product_description:
    label: Product Description
    type: textarea
  product_photo:
    label: Product Photo
    type: select
    options: files
