title: Site
pages:
  template:
    - home
    - members
    - shop
    - contact
files: true
fields:
  title:
    label: Site Name

  section_seo:
    label: SEO
    type: headline

  keywords:
    label: Keywords
    type: tags
  description:
    label: Description
    type: textarea
    buttons: false
    help: >
      To be used in the description Meta tag. Keep this short, preferably under 160 characters.

  section_footer:
    label: Footer Section
    type: headline

  social:
    label: Social
    type: structure
    style: table
    entry: >
      <strong>{{service}}</strong><br />
      {{link}}
    fields:
      service:
        label: Service
        type: text
      link:
        label: Link
        type: url


